version: '3.1'

services:

  db:
    build:
      context: ./database
      args:
        DATABASE_NAME: contact-manager
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database_data:/var/lib/mysql
    ports:
      - 3306
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: contact-manager
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    networks:
      - db-network
  
  backend:
    build:
      context: ./backend
    restart: always
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: db
      DATABASE_USER: root
      DATABASE_PASSWORD: "${DB_PASSWORD}"
      DATABASE_DB: contact-manager 
    networks:
      - db-network
      - frontend-backend

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
      - backend
    networks:
      - frontend-backend


networks:
  db-network:
  frontend-backend:
